services:
  web:
    build:
      context: .
      dockerfile: Docker/Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=$DATABASE_URL
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY
      - SUPABASE_URL=$SUPABASE_URL
      - SUPABASE_SERVICE_ROLE_KEY=$SUPABASE_SERVICE_ROLE_KEY
